"""The shared value corpus, run against this codec in BOTH directions.

Decoding alone does not check a codec. One that is wrong in the same way on both
sides round-trips perfectly — mutating both halves of the i64 inversion is
invisible to any test this repository could write about itself. The corpus is
generated by a separate implementation written from the specification alone,
which makes it the only external anchor available.
"""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from corpus import read_corpus, same_value, value_of  # noqa: E402

from tessaridb import ProtocolError, decode, encode  # noqa: E402

CASES_WHEN_WRITTEN = 54


class ValueCorpus(unittest.TestCase):
    def test_every_vector_encodes_and_decodes_exactly(self) -> None:
        corpus = read_corpus("values-v1.json")
        cases = corpus["cases"]
        self.assertGreaterEqual(
            len(cases),
            CASES_WHEN_WRITTEN,
            "the corpus shrank — a suite cannot get stronger by losing vectors",
        )

        for case in cases:
            with self.subTest(case["name"]):
                expected = bytes.fromhex(case["bytes"])
                value = value_of(case["value"])

                self.assertEqual(
                    encode(value).hex(),
                    expected.hex(),
                    "encoded bytes differ from the corpus",
                )
                self.assertTrue(
                    same_value(value, decode(expected)),
                    f"decoded value differs: {decode(expected)!r}",
                )

    def test_a_payload_with_trailing_bytes_is_refused(self) -> None:
        # After one value the buffer must be exhausted. Ignoring what is left
        # turns a framing bug into a value that looks fine.
        with self.assertRaises(ProtocolError):
            decode(bytes.fromhex("01") + b"\x00")

    def test_an_unknown_tag_is_an_error_rather_than_a_guess(self) -> None:
        with self.assertRaises(ProtocolError):
            decode(b"\xff")

    def test_nanoseconds_outside_the_sub_second_range_are_an_error_not_a_wrap(self) -> None:
        from tessaridb import Duration

        with self.assertRaises(ProtocolError):
            encode(Duration(0, 1_000_000_000))

    def test_an_integer_beyond_i64_is_refused_rather_than_truncated(self) -> None:
        # Python's int is arbitrary precision, so this is the one check the other
        # clients get from their types and this one has to make for itself.
        from tessaridb import Integer

        with self.assertRaises(ProtocolError):
            encode(Integer(2**63))
        with self.assertRaises(ProtocolError):
            encode(Integer(-(2**63) - 1))


if __name__ == "__main__":
    unittest.main()
